### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ricky-chaoju** [nicedaddy/yolov3_deepsort_lane_detection#1]
Hello:
I get the following error after running the program.
Runs on M1 Max Macbook and Windows.
thanks

Traceback (most recent call last):
  File "/Users/rickychen/Downloads/carcopy/object_tracker.py", line 163, in <module>
    app.run(main)
  File "/Users/rickychen/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/rickychen/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/rickychen/Downloads/carcopy/object_tracker.py", line 41, in main
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "/Users/rickychen/Downloads/carcopy/tools/generate_detections.py", line 103, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/Users/rickychen/Downloads/carcopy/tools/generate_detections.py", line 83, in __init__
    self.input_var = tf.get_default_graph().get_tensor_by_name(
  File "/Users/rickychen/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 4174, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/Users/rickychen/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3998, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/Users/rickychen/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 4038, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

**Comment by ricky-chaoju** [comment]
https://vimeo.com/766339571/367fa3a4c4

**Comment by Dhathri19** [comment]
I am getting the same error.
Traceback (most recent call last):
  File "/content/yolov3_deepsort_lane_detection/object_tracker.py", line 221, in <module>
    app.run(main)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/yolov3_deepsort_lane_detection/object_tracker.py", line 57, in main
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "/content/yolov3_deepsort_lane_detection/tools/generate_detections.py", line 103, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "/content/yolov3_deepsort_lane_detection/tools/generate_detections.py", line 83, in __init__
    self.input_var = tf.get_default_graph().get_tensor_by_name(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 4188, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 4012, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 4052, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'net/images:0' refers to a Tensor which does not exist. The operation, 'net/images', does not exist in the graph."

Please help

**Comment by nicedaddy** [comment]
Hello, Dhathri,

Checking the issue for you. I will feedback and update for you

Thanks

Dean

2023년 7월 5일 (수) 오후 4:44, Dhathri Meda ***@***.***>님이 작성:
